### ISSUE TITLE
FYI: your tool as a Docker image

### ISSUE THREAD

**Issue by eugene-taylashev** [benapetr/dnsphpadmin#19]
Hi Petr, 
this is not an issue, but For Your Information (FYI). 
I put some code to run your tool as a Docker image:

- GitHub: https://github.com/eugene-taylashev/docker-dnsphpadmin
- Docker Hub: https://hub.docker.com/repository/docker/etaylashev/dnsphpadmin

Thanks for the tool
Regards
Eugene

**Comment by benapetr** [comment]
Hello,

Thanks, added mention here: https://github.com/benapetr/dnsphpadmin/tree/master#docker-image
