### ISSUE TITLE
TSIG Key... How?

### ISSUE THREAD

**Issue by JSylvia007** [benapetr/dnsphpadmin#20]
I can't figure out the proper way to enter the TSIG key required...  Is it a string to a file?  Where does the file need to be?  Do I copy the full contents of the key into the string variable?  Any help would be awesome.  This is the last thing I need to get through.

**Comment by JSylvia007** [comment]
I still haven't figured out how to get TSIG keys to work, but something tells me that there's an issue on my end.  I can't even get dnssec-keygen to generate something.  every combination I try fails.

I'm using ACLs as this is for my homelab, and it's at least working for now.

**Comment by benapetr** [comment]
hello,

if you already have a TSIG key generated, then there are two ways you can integrate them. And yes for both of them you need to load the secrets into a variable, you can either add it to main config file, or you can put it to separate file and then include it in the main config file, or you can even use some function to load it from the file into the string. PHP is very flexible in this.

So, there are 2 ways - global config that applies to all zones:

```
$g_tsig = true;
$g_tsig_key = 'secret_private_key';
```

Local config per zone

in `$g_domains` configure a zone like this:
```
$g_domains = [ 'example.domain' => [ 'transfer_server' => 'localhost',
                                      'update_server' => 'localhost',
                                      'tsig' => true,
                                      'tsig_key' => 'some_key' ] ];
```

**Comment by JSylvia007** [comment]
So... I get that... but it doesn't tell you what the value of tsig_key should look like...  It APPEARS like it should be "algorithm:key_name:key_string".  I think that's the case because I saw how the website was passing the information down to the command line in debug mode.

I say "THINK", because I can't get dnssec-keygen to even generate ANY kind of key, and any of the tsig-keygen keys that I generate also don't work from the command line with nsupdate.

Since this is for my homelab, ACLs should be good enough, but I would like to figure out what I'm doing wrong, and how the hell I can actually generate a key with dnssec-keygen.  There is literally NO (valuable) information on using that tool and no matter what string of options I put together, I can't make it generate a key.

**Comment by benapetr** [comment]
it's the value that nsupdate needs for its key statement, that is the value inside of .private file generated by dnssec-keygen command in the `Key:` section

**Comment by benapetr** [comment]
here is excerpt from nsupdate manual page:

       key [hmac:] {keyname} {secret}
           Specifies that all updates are to be TSIG-signed using the keynamesecret pair. If hmac is specified, then it sets the signing algorithm in use; the default is hmac-md5 or if MD5 was disabled hmac-sha256. The key command
           overrides any key specified on the command line via -y or -k.
           
           
dnsphpadmin will send payload `key $tsig_value_from_config`to the nsupdate

**Comment by JSylvia007** [comment]
> here is excerpt from nsupdate manual page:
> 
> ```
>    key [hmac:] {keyname} {secret}
>        Specifies that all updates are to be TSIG-signed using the keynamesecret pair. If hmac is specified, then it sets the signing algorithm in use; the default is hmac-md5 or if MD5 was disabled hmac-sha256. The key command
>        overrides any key specified on the command line via -y or -k.
> ```
> 
> dnsphpadmin will send payload `key $tsig_value_from_config`to the nsupdate

Yep, this is what I've been able to determine.  Thanks for the clarification.  I still can't generate keys with dnssec-keygen, but this isn't your issue.  I will close this ticket.  

Thank you for creating a simple, effective tool!!
